Java team's branch merge to main
NeoSOFT-Technologies/console pull request #232
Opened 2022-06-13 07:55 UTC by pillai-karthik

2022-06-13 08:02 UTC, paras-1999 commented on src/components/list/RenderTableList.tsx
> +interface IProps {
don't write interface here inside type> index and then import

2022-06-13 08:07 UTC, paras-1999 commented on src/AppRoutes.tsx
> +import GetTables from "./pages/features/saas/get-tables/GetTables";
do lazy loading over here

2022-06-13 08:15 UTC, paras-1999 commented on src/pages/features/saas/manage-table/ManageTable.tsx
> +    <div className="createbody">
use conditional rendering for the loading and error page

2022-06-13 08:25 UTC, paras-1999 commented on src/pages/features/saas/search-data/SearchData.tsx
> +    <div>
do conditional rendering

2022-06-13 08:31 UTC, paras-1999 requested changes
look for the inline comments that i add regarding the conditional rendering and interface

2022-06-13 09:10 UTC, mihir-neosoft requested changes
.vscode files are unnecessary.
Try to avoid using any as type.
Take pull from main regularly.

2022-06-13 09:10 UTC, mihir-neosoft commented on src/pages/features/saas/search-data/SearchData.tsx
> +  const [tenantId, setTenantId] = useState("");
combine states in possible

2022-06-15 13:55 UTC, mihir-neosoft commented on src/pages/features/saas/add-table/CreateTable.tsx
> +  const toUppercase = (str: string) => {
Please make a util file and add this tyeof function in that

2022-06-16 05:23 UTC, ojahagirdar commented on src/pages/features/saas/search-data/SearchData.tsx
> +    <div>
resolved

2022-07-01 06:16 UTC, mangeshdase approved these changes

2022-07-06 08:27 UTC, santoshshinde2012 approved these changes

2022-07-06 08:27 UTC, merged